Fixed a bug where I got a NoClassDefFoundError when I'm using a build-local.properties where I set optional.lib.dir to an absolute Windows path. These absolute paths weren't removed somehow resulting in NoClassDefFound errors due to a illegal Class-Path entry in fop.jar's manifest.
git-svn-id: https://svn.apache.org/repos/asf/xmlgraphics/fop/trunk@197247 13f79535-47bb-0310-9956-ffa450edef68