Fix NoSuchMethodError when FOP is compiled under JDK1.4 but run under JDK1.3. Reason: StringBuffer.append(StringBuffer) has been added with JDK1.4.
git-svn-id: https://svn.apache.org/repos/asf/xmlgraphics/fop/branches/fop-0_20_2-maintain@196492 13f79535-47bb-0310-9956-ffa450edef68